// Workflow State Machine Constants & Enums

export const WORKFLOW_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  FAILED: 'FAILED',      // retryable — NOT terminal
  COMPLETED: 'COMPLETED',
};


//Task states
export const TASK_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  FAILED: 'FAILED',      // retryable — NOT terminal
  COMPLETED: 'COMPLETED',
};

//Checkpoint states
export const CHECKPOINT_STATUS = {
  WAITING_FOR_ANSWER: 'WAITING_FOR_ANSWER',
  ANSWERED: 'ANSWERED',
  EVALUATED: 'EVALUATED',
};

//Verdict states
export const VERDICT = {        // was JEV_VERDICT
  PASSED: 'PASSED',
  PARTIAL: 'PARTIAL',
  MISCONCEPTION: 'MISCONCEPTION',
};

//Commands the engine accepts
export const COMMAND = {
  START_WORKFLOW: 'START_WORKFLOW',
  PAUSE_WORKFLOW: 'PAUSE_WORKFLOW',
  RESUME_WORKFLOW: 'RESUME_WORKFLOW',
  RETRY_WORKFLOW: 'RETRY_WORKFLOW',
  ACTIVATE_TASK: 'ACTIVATE_TASK',
  PRESENT_CHECKPOINT: 'PRESENT_CHECKPOINT',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  EVALUATE_CHECKPOINT: 'EVALUATE_CHECKPOINT',
  ABANDON_TASK: 'ABANDON_TASK',
};

//Error codes
export const ERROR_CODE = {
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  WORKFLOW_VERSION_CONFLICT: 'WORKFLOW_VERSION_CONFLICT',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
};