import { Check, Clipboard, CornerDownLeft, X, Sparkles, FileText, RotateCw, Lightbulb, Pencil } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { AssistResult } from "@/components/ai/types";
import { useState } from "react";
import { cn } from "@/lib/utils";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import rehypeRaw from "rehype-raw";
import "katex/dist/katex.min.css";
import { sanitizeStream } from "@/utils/streamSanitizer";
import { sharedMarkdownComponents } from "@/utils/sharedMarkdownComponents";



type AiResultDialogProps = {
  result: AssistResult | null;
  onApply: () => void;
  onClose: () => void;
};

const AiResultDialog = ({ result, onApply, onClose }: AiResultDialogProps) => {
  const [copied, setCopied] = useState(false);

  if (!result) return null;

  const isDialogAction = ["summarize", "explain", "rewrite", "noteCreation"].includes(result.action);
  if (!isDialogAction) return null;

  const getActionTitle = () => {
    switch (result.action) {
      case "summarize": return "AI Summary";
      case "explain": return "AI Explanation";
      case "noteCreation": return "AI Note Creator";
      case "rewrite": return "AI Polish";
      default: return "AI Insight";
    }
  };

  const getActionIcon = () => {
    switch (result.action) {
      case "summarize": return <FileText size={18} className="text-blue-500" />;
      case "explain": return <Lightbulb size={18} className="text-amber-500" />;
      case "noteCreation": return <Pencil size={18} className="text-green-500" />;
      case "rewrite": return <RotateCw size={18} className="text-emerald-500" />;
      default: return <Sparkles size={18} className="text-blue-500" />;
    }
  };

  const getActionDescription = () => {
    switch (result.action) {
      case "summarize": return "A concise breakdown of your note's key points.";
      case "explain": return "Deep dive explanation to help you understand better.";
      case "rewrite": return "A polished version with improved flow and clarity.";
      case "noteCreation": return "A newly generated note based on the content and context of your selection.";
      default: return "Insights generated by Iris AI.";
    }
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(result.suggestion);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog open={true} onOpenChange={(open) => !open && onClose()}>
      <DialogContent 
        className="max-w-xl p-0 gap-0 overflow-hidden border-none bg-transparent shadow-2xl"
        showCloseButton={false}
      >
        <div className="flex flex-col bg-[var(--panel-bg)] border border-[var(--divider)] rounded-3xl overflow-hidden shadow-2xl animate-in fade-in zoom-in-95 duration-200">
          <DialogHeader className="px-6 py-5 border-b border-[var(--divider)] bg-[var(--panel-bg-strong)] flex-row items-center justify-between space-y-0">
            <div className="flex items-center gap-4">
              <div className="p-2.5 rounded-xl bg-[var(--surface-ghost)] shadow-sm border border-[var(--divider)]">
                {getActionIcon()}
              </div>
              <div className="flex flex-col">
                <DialogTitle className="text-base font-bold text-[var(--text-strong)] tracking-tight antialiased">
                  {getActionTitle()}
                </DialogTitle>
                <DialogDescription className="text-xs text-[var(--muted-text)] font-medium mt-0.5">
                  {getActionDescription()}
                </DialogDescription>
              </div>
            </div>
            <button 
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-[var(--surface-ghost)] text-[var(--muted-text)] transition-all hover:rotate-90"
            >
              <X size={18} />
            </button>
          </DialogHeader>

          <div className="p-8 max-h-[60vh] overflow-y-auto custom-scrollbar bg-[var(--panel-bg)] selection:bg-[var(--accent-strong)]/30">
            <div className="gc-markdown text-[var(--text-strong)] max-w-full">
               <ReactMarkdown
                remarkPlugins={[remarkGfm, remarkMath]}
                rehypePlugins={[rehypeRaw, rehypeKatex]}
                components={sharedMarkdownComponents()}
               >
                 {sanitizeStream(result.suggestion)}
               </ReactMarkdown>
               {result.isStreaming && (
                 <span className="gc-cursor" aria-hidden="true" />
               )}
            </div>
          </div>

          <DialogFooter className="px-5 py-4 border-t border-[var(--divider)] bg-[var(--panel-bg-strong)] flex flex-row items-center justify-between sm:justify-between">
            <div className="flex items-center gap-2">
               <Button
                variant="outline"
                size="sm"
                onClick={copyToClipboard}
                disabled={result.isStreaming}
                className="gap-2 h-9 rounded-xl border-[var(--divider)] bg-[var(--surface-muted)] hover:bg-[var(--surface-ghost)] text-[var(--text-strong)] disabled:opacity-50"
              >
                {copied ? <Check size={14} className="text-green-500" /> : <Clipboard size={14} />}
                {copied ? "Copied" : "Copy result"}
              </Button>
            </div>
            
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="h-9 rounded-xl text-[var(--muted-text)] hover:bg-[var(--surface-ghost)]"
              >
                Dismiss
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  onApply();
                  onClose();
                }}
                disabled={result.isStreaming}
                className={cn(
                  "gap-2 h-9 rounded-xl px-4 font-semibold shadow-sm disabled:opacity-50",
                  result.action === "rewrite" ? "bg-emerald-600 hover:bg-emerald-700 text-white" : "bg-blue-600 hover:bg-blue-700 text-white"
                )}
              >
                <CornerDownLeft size={14} />
                {result.action === "rewrite" ? "Replace selection" : "Insert at cursor"}
              </Button>
            </div>
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default AiResultDialog;
